"use client";
import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useCart } from "@/lib/cart-store";
import { money } from "@/lib/utils";
import { buildWhatsAppMessage } from "@/lib/cart-to-whatsapp";
import { createClient, hasSupabaseEnv } from "@/lib/supabase/client";
import { EmptyState } from "@/components/ui/empty-state";
export default function CartPage(){const {items,remove,setQuantity,clear}=useCart();const total=items.reduce((s,i)=>s+i.price*i.quantity,0);
  async function submit(){if(!items.length)return;const campaign=localStorage.getItem("active_campaign_slug");let userId:string|undefined;if(hasSupabaseEnv){const db=createClient();const {data}=await db.auth.getUser();userId=data.user?.id;void db.from("cart_submissions").insert({user_id:userId??null,items:items.map(i=>({product_id:i.productId,name:i.name,variation_label:i.variationLabel,qty:i.quantity,price:i.price})),estimated_total:total,campaign_slug:campaign});}
    const message=buildWhatsAppMessage(items);const number=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||"212600000000";clear();window.location.href=`https://wa.me/${number}?text=${encodeURIComponent(message)}`;}
  if(!items.length)return <div className="container-shell py-20"><EmptyState title="Votre panier est vide" text="Découvrez notre sélection d’instruments et ajoutez ce qu’il vous faut."/></div>;
  return <div className="container-shell py-14"><p className="eyebrow">Votre sélection</p><h1 className="display mt-3 text-5xl">Le panier</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="grid gap-3">{items.map(i=><div key={i.key} className="card flex items-center gap-4 p-4">{i.image&&<div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-white"><Image src={i.image} fill alt="" className="object-cover"/></div>}<div className="min-w-0 flex-1"><Link href={`/product/${i.slug}`} className="font-bold">{i.name}</Link>{i.variationLabel&&<p className="mt-1 text-xs text-ink/45">{i.variationLabel}</p>}<p className="mt-2 text-sm font-bold text-sage">{money(i.price)}</p></div><div className="flex items-center rounded-full border border-ink/15 bg-white"><button aria-label="Réduire" className="p-2" onClick={()=>setQuantity(i.key,i.quantity-1)}><Minus size={14}/></button><span className="w-7 text-center text-sm font-bold">{i.quantity}</span><button aria-label="Augmenter" className="p-2" onClick={()=>setQuantity(i.key,i.quantity+1)}><Plus size={14}/></button></div><button aria-label="Supprimer" onClick={()=>remove(i.key)} className="p-2 text-ink/35 hover:text-coral"><Trash2 size={18}/></button></div>)}</div>
    <aside className="card h-fit p-6 lg:sticky lg:top-28"><h2 className="display text-2xl">Récapitulatif</h2><div className="mt-6 grid gap-3 border-b border-ink/10 pb-5 text-sm"><div className="flex justify-between"><span className="text-ink/55">Articles</span><span>{items.reduce((s,i)=>s+i.quantity,0)}</span></div><div className="flex justify-between"><span className="text-ink/55">Livraison</span><span>À convenir</span></div></div><div className="flex justify-between py-6 text-lg font-bold"><span>Total estimé</span><span>{money(total)}</span></div><button onClick={submit} className="button w-full !bg-[#1f9d55]">Confirmer sur WhatsApp</button><p className="mt-4 flex gap-2 text-xs leading-5 text-ink/45"><ShieldCheck size={28}/> Aucun paiement en ligne. Vous finalisez les détails directement avec notre conseiller.</p></aside>
  </div></div>}
