import { ClipboardList, MessageCircle, PackageCheck } from "lucide-react";
import { AccountShell } from "@/components/account/account-shell";
import { requireAccount } from "@/lib/account-server";
import { money } from "@/lib/utils";

const statusLabels={saved_submission:"Demande enregistrée",whatsapp_handoff:"Transmise à WhatsApp",confirmed_order:"Commande confirmée"} as const;
export default async function OrdersPage(){const {db,isAdmin}=await requireAccount();const {data}=await db.from("cart_submissions").select("id,items,estimated_total,status,delivery_city,delivery_address,created_at").order("created_at",{ascending:false});return <AccountShell isAdmin={isAdmin} title="Mes demandes et commandes">
  <div className="account-panel mb-5 p-5 text-sm leading-6 text-white/55"><b className="text-white">Comprendre les statuts</b><div className="mt-3 grid gap-2 md:grid-cols-3"><span>Demande enregistrée : sauvegardée.</span><span>Transmise à WhatsApp : conversation ouverte.</span><span>Commande confirmée : validée par DENTANOVA.</span></div></div>
  {!data?.length?<div className="account-empty"><ClipboardList/><h2>Aucune demande enregistrée</h2><p>Vos demandes réelles apparaîtront ici après un envoi depuis le panier.</p></div>:<div className="grid gap-4">{data.map(row=><article key={row.id} className="account-panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-cyan-300">Référence {String(row.id).slice(0,8).toUpperCase()}</p><p className="mt-2 text-sm text-white/45">{new Date(row.created_at).toLocaleString("fr-MA")}</p></div><span className="account-badge">{row.status==="confirmed_order"?<PackageCheck size={14}/>:<MessageCircle size={14}/>} {statusLabels[row.status as keyof typeof statusLabels]||"Demande enregistrée"}</span></div><div className="mt-5 grid gap-2">{(row.items as any[]||[]).map((item,index)=><div key={`${item.product_id}-${index}`} className="flex justify-between gap-4 border-t border-white/[.07] pt-3 text-sm"><span>{item.name}{item.variation_label?` · ${item.variation_label}`:""} × {item.qty||item.quantity}</span><b>{money(Number(item.price)*(item.qty||item.quantity||1))}</b></div>)}</div><div className="mt-5 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-4"><span className="text-sm text-white/50">Livraison : {row.delivery_city||"Casablanca"}</span><strong>Total estimé : {money(Number(row.estimated_total||0))}</strong></div></article>)}</div>}
</AccountShell>}
