"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient, hasSupabaseEnv } from "@/lib/supabase/client";
function GoogleIcon(){return <svg width="18" height="18" viewBox="0 0 18 18" aria-hidden="true"><path fill="#4285F4" d="M17.64 9.2c0-.64-.06-1.25-.16-1.84H9v3.48h4.84a4.14 4.14 0 0 1-1.8 2.72v2.26h2.9c1.7-1.57 2.68-3.87 2.68-6.62Z"/><path fill="#34A853" d="M9 18c2.43 0 4.47-.8 5.96-2.18l-2.9-2.26c-.8.54-1.83.86-3.06.86-2.35 0-4.34-1.59-5.05-3.72H.95v2.33A9 9 0 0 0 9 18Z"/><path fill="#FBBC05" d="M3.95 10.7A5.4 5.4 0 0 1 3.67 9c0-.59.1-1.16.28-1.7V4.97H.95A9 9 0 0 0 0 9c0 1.45.35 2.83.95 4.03l3-2.33Z"/><path fill="#EA4335" d="M9 3.58c1.32 0 2.51.46 3.44 1.35l2.58-2.58C13.46.89 11.43 0 9 0A9 9 0 0 0 .95 4.97l3 2.33C4.66 5.17 6.65 3.58 9 3.58Z"/></svg>}
export function AuthForm(){const [mode,setMode]=useState<"login"|"signup">("login"),[message,setMessage]=useState(""),router=useRouter();
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),email=String(form.get("email")),password=String(form.get("password")),full_name=String(form.get("full_name")||"");if(!hasSupabaseEnv){setMessage("Le service de connexion est temporairement indisponible.");return}const db=createClient();const result=mode==="login"?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password,options:{data:{full_name}}});if(result.error)setMessage(mode==="login"?"E-mail ou mot de passe incorrect.":"Impossible de créer le compte. Vérifiez les informations saisies.");else {setMessage(mode==="signup"?"Vérifiez votre boîte mail pour confirmer votre compte.":"Connexion réussie.");router.push(mode==="login"?"/account/profile":"/");router.refresh()}}
  async function recover(){const email=(document.querySelector<HTMLInputElement>('input[name="email"]')?.value||"").trim();if(!email){setMessage("Saisissez votre adresse e-mail.");return}const {error}=await createClient().auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/account/security`});setMessage(error?"Impossible d’envoyer le lien de récupération.":"Lien de récupération envoyé par e-mail.")}
  async function withGoogle(){if(!hasSupabaseEnv){setMessage("Le service de connexion est temporairement indisponible.");return}const {error}=await createClient().auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error)setMessage("Impossible de se connecter avec Google.")}
return <div className="account-panel p-7 text-white"><div className="mb-6 grid grid-cols-2 rounded-full bg-white/[.05] p-1 text-sm font-bold"><button type="button" onClick={()=>setMode("login")} className={`rounded-full py-2 ${mode==="login"?"bg-white text-[#091018] shadow":""}`}>Connexion</button><button type="button" onClick={()=>setMode("signup")} className={`rounded-full py-2 ${mode==="signup"?"bg-white text-[#091018] shadow":""}`}>Créer un compte</button></div>
<button type="button" onClick={withGoogle} className="mb-4 flex w-full items-center justify-center gap-3 rounded-full border border-white/15 bg-white/[.04] py-3 text-sm font-bold text-white transition hover:bg-white/[.08]"><GoogleIcon/>Continuer avec Google</button>
<div className="mb-4 flex items-center gap-3 text-xs font-bold text-white/35"><span className="h-px flex-1 bg-white/10"/>OU<span className="h-px flex-1 bg-white/10"/></div>
<form onSubmit={submit} className="grid gap-4">{mode==="signup"&&<label className="account-field">Nom complet<input required name="full_name" placeholder="Votre nom"/></label>}<label className="account-field">E-mail<input required type="email" name="email" placeholder="vous@exemple.ma"/></label><label className="account-field">Mot de passe<input required minLength={10} type="password" name="password" placeholder="10 caractères minimum"/></label>{mode==="login"&&<button type="button" onClick={recover} className="justify-self-start text-xs font-bold text-cyan-300 hover:text-cyan-200">Mot de passe oublié ?</button>}<button className="account-button mt-2">{mode==="login"?"Se connecter":"Créer mon compte"}</button>{message&&<p role="status" className="account-feedback">{message}</p>}</form></div>}
