"use client";
import { CheckCircle2, MapPin, Save } from "lucide-react";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { validateMoroccanAddress } from "@/lib/account-validation";
type Address={id?:string;recipient_name?:string;phone?:string;address_line?:string;district?:string;postal_code?:string|null;delivery_instructions?:string|null;city?:string};
export function DeliveryForm({initial}:{initial:Address|null}){const [message,setMessage]=useState(""),[errors,setErrors]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),result=validateMoroccanAddress({recipient_name:String(f.get("recipient_name")||""),phone:String(f.get("phone")||""),address_line:String(f.get("address_line")||""),district:String(f.get("district")||""),postal_code:String(f.get("postal_code")||""),delivery_instructions:String(f.get("delivery_instructions")||""),city:String(f.get("city")||"")});if(!result.valid){setErrors(result.errors);return}setSaving(true);setErrors({});const db=createClient(),{data:{user}}=await db.auth.getUser();if(!user)return;const payload={...result.data,user_id:user.id,is_default:true};const response=initial?.id?await db.from("delivery_addresses").update(payload).eq("id",initial.id).eq("user_id",user.id):await db.from("delivery_addresses").insert(payload);setMessage(response.error?"Impossible d’enregistrer l’adresse.":"Adresse de livraison enregistrée.");setSaving(false)}
const field=(name:string,label:string,type="text")=><label className="account-field">{label}<input name={name} type={type} defaultValue={(initial as Record<string,unknown>|null)?.[name] as string||""}/>{errors[name]&&<small role="alert">{errors[name]}</small>}</label>;
return <form onSubmit={submit} className="account-panel grid gap-5 p-6 sm:grid-cols-2"><div className="sm:col-span-2 rounded-2xl border border-cyan-300/20 bg-cyan-300/[.07] p-4"><p className="flex items-center gap-2 font-bold"><MapPin className="text-cyan-300" size={18}/>Livraison disponible partout au Maroc.</p><p className="mt-1 text-sm text-white/45">Indiquez votre ville pour organiser la livraison.</p></div>{field("recipient_name","Nom du destinataire")}{field("phone","Téléphone","tel")}<label className="account-field sm:col-span-2">Adresse<input name="address_line" defaultValue={initial?.address_line||""}/>{errors.address_line&&<small>{errors.address_line}</small>}</label>{field("district","Quartier")}{field("postal_code","Code postal")}<label className="account-field sm:col-span-2">Instructions de livraison<textarea name="delivery_instructions" rows={4} defaultValue={initial?.delivery_instructions||""}/></label>{field("city","Ville")}<div className="flex items-end"><button disabled={saving} className="account-button w-full"><Save size={17}/>{saving?"Enregistrement…":"Enregistrer l’adresse"}</button></div>{message&&<p role="status" className="account-feedback sm:col-span-2"><CheckCircle2 size={18}/>{message}</p>}</form>}
