import Link from "next/link";
import { ArrowRight, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { getCatalog } from "@/lib/data";
import { ProductCard } from "@/components/storefront/product-card";
export default async function Home(){const {products,categories,offers,campaigns}=await getCatalog();const campaign=campaigns[0];return <>
  <section className="container-shell py-8 lg:py-14"><div className="relative overflow-hidden rounded-[2rem] bg-ink px-7 py-16 text-white md:px-14 md:py-24">
    <div className="absolute -right-20 -top-28 h-96 w-96 rounded-full bg-sage/70 blur-3xl"/><div className="absolute bottom-[-120px] right-[22%] h-80 w-80 rounded-full bg-coral/25 blur-3xl"/>
    <div className="relative max-w-2xl"><p className="eyebrow !text-mint">La précision au quotidien</p><h1 className="display mt-5 text-5xl leading-[.98] md:text-7xl">Bien équipé.<br/><i className="font-normal text-mint">Prêt à soigner.</i></h1><p className="mt-6 max-w-lg text-base leading-7 text-white/65">Des instruments sélectionnés avec soin, du premier TP à la pratique en cabinet. Commandez simplement via WhatsApp.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#selection" className="button !bg-white !text-ink">Voir la sélection <ArrowRight size={18}/></Link><Link href="/category/diagnostic" className="button !border-white/20 !bg-white/10">Explorer les catégories</Link></div></div>
    <div className="relative mt-14 grid gap-3 border-t border-white/10 pt-6 text-xs text-white/60 sm:grid-cols-3"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-mint"/> Matériel sélectionné</span><span className="flex items-center gap-2"><Truck size={17} className="text-mint"/> Livraison partout au Maroc</span><span className="flex items-center gap-2"><Sparkles size={17} className="text-mint"/> Conseil humain</span></div>
  </div></section>
  {campaign&&<section className="container-shell"><Link href={campaign.banner_link||"/"} className="group flex flex-col justify-between gap-6 overflow-hidden rounded-[1.5rem] bg-coral px-7 py-7 text-white sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em]">Offre du moment</p><h2 className="display mt-2 text-3xl">{campaign.name}</h2></div><span className="flex items-center gap-2 font-bold">En profiter <ArrowRight className="transition group-hover:translate-x-1"/></span></Link></section>}
  <section className="container-shell py-20"><div className="flex items-end justify-between"><div><p className="eyebrow">Par discipline</p><h2 className="display mt-2 text-4xl md:text-5xl">Trouvez votre essentiel</h2></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{categories.slice(0,4).map((c,i)=><Link key={c.id} href={`/category/${c.slug}`} className={`group min-h-40 rounded-[1.3rem] p-5 ${i%3===0?"bg-mint":i%3===1?"bg-white":"bg-[#e8dfd1]"}`}><span className="text-xs font-bold text-ink/45">0{i+1}</span><h3 className="display mt-14 text-2xl">{c.name}</h3><ArrowRight className="mt-2 transition group-hover:translate-x-1" size={18}/></Link>)}</div></section>
  <section id="selection" className="container-shell"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Notre sélection</p><h2 className="display mt-2 text-4xl md:text-5xl">Les incontournables</h2></div><Link href="/search" className="hidden text-sm font-bold sm:block">Tout voir →</Link></div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.filter(p=>p.is_featured).slice(0,8).map(p=><ProductCard key={p.id} product={p} offers={offers}/>)}</div></section>
</>}
