"use client";
import { useMemo, useState } from "react";
import { Check, ShoppingBag } from "lucide-react";
import Image from "next/image";
import type { Product } from "@/lib/types";
import { useCart } from "@/lib/cart-store";
import { money } from "@/lib/utils";
export function AddToCart({product,price}:{product:Product;price:number}){const activeVariations=useMemo(()=>product.variations?.filter(v=>v.is_active!==false)||[],[product.variations]);const [variation,setVariation]=useState<typeof activeVariations[number] | undefined>();const [added,setAdded]=useState(false);const add=useCart(s=>s.add);const final=variation?Number(variation.price):price;const selectionRequired=activeVariations.length>0&&!variation;const productUnavailable=["out_of_stock","unavailable"].includes(product.availability_status||product.stock_status)||(product.stock_tracking&&activeVariations.length===0&&Number(product.stock_quantity||0)<=0);const variationUnavailable=Boolean(variation&&(variation.availability==="out_of_stock"||(typeof variation.stock_quantity==="number"&&variation.stock_quantity<=0)));const unavailable=selectionRequired||productUnavailable||variationUnavailable;return <div>
  {activeVariations.length>0&&<div className="mb-6"><label className="mb-2 block text-sm font-bold">Choisir une variation</label><div className="flex flex-wrap gap-2">{activeVariations.map(v=>{const disabled=v.availability==="out_of_stock"||(typeof v.stock_quantity==="number"&&v.stock_quantity<=0);return <button type="button" key={v.id||v.label} disabled={disabled} onClick={()=>setVariation(v)} className={`rounded-full border px-4 py-2 text-sm transition disabled:cursor-not-allowed disabled:opacity-35 ${variation?.id===v.id&&variation?.label===v.label?"border-cyan-300 bg-cyan-300 text-[#061017]":"border-white/15 bg-white/[.04] text-white hover:border-cyan-300/40"}`}>{v.label} · {money(Number(v.price))}</button>})}</div>{variation&&<div className="mt-4 flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.03] p-3">{variation.image_url&&<span className="relative h-14 w-14 overflow-hidden rounded-lg"><Image src={variation.image_url} alt={`${product.name} — ${variation.label}`} fill className="object-cover"/></span>}<div className="text-sm"><b>{variation.label}</b>{variation.sku&&<p className="text-xs text-white/45">SKU · {variation.sku}</p>}<p className="text-cyan-300">{money(Number(variation.price))}</p></div></div>}</div>}
  <button disabled={unavailable} onClick={()=>{add({productId:product.id,slug:product.slug,name:product.name,image:variation?.image_url||product.images?.[0],variationId:variation?.id,variationSku:variation?.sku,variationLabel:variation?.label,price:final});setAdded(true);setTimeout(()=>setAdded(false),1600)}} className="button w-full disabled:cursor-not-allowed disabled:opacity-40">{selectionRequired?"Choisissez une variation":unavailable?"Indisponible":added?<><Check size={19}/>Ajouté au panier</>:<><ShoppingBag size={19}/>Ajouter · {money(final)}</>}</button>
</div>}
