"use client";
import { useMemo, useState } from "react";
import { Check, ShoppingBag } from "lucide-react";
import type { Product } from "@/lib/types";
import { useCart } from "@/lib/cart-store";
import { money } from "@/lib/utils";
export function AddToCart({product,price}:{product:Product;price:number}){const activeVariations=useMemo(()=>product.variations?.filter(v=>v.is_active!==false)||[],[product.variations]);const [variation,setVariation]=useState(activeVariations[0]);const [added,setAdded]=useState(false);const add=useCart(s=>s.add);const final=variation?Number(variation.price):price;const productUnavailable=["out_of_stock","unavailable"].includes(product.availability_status||product.stock_status)||(product.stock_tracking&&Number(product.stock_quantity||0)<=0);const variationUnavailable=Boolean(variation&&(variation.availability==="out_of_stock"||(typeof variation.stock_quantity==="number"&&variation.stock_quantity<=0)));const unavailable=productUnavailable||variationUnavailable;return <div>
  {activeVariations.length>0&&<div className="mb-6"><label className="mb-2 block text-sm font-bold">Choisir une variation</label><div className="flex flex-wrap gap-2">{activeVariations.map(v=>{const disabled=v.availability==="out_of_stock"||(typeof v.stock_quantity==="number"&&v.stock_quantity<=0);return <button key={v.id||v.label} disabled={disabled} onClick={()=>setVariation(v)} className={`rounded-full border px-4 py-2 text-sm transition disabled:cursor-not-allowed disabled:opacity-35 ${variation?.id===v.id&&variation?.label===v.label?"border-cyan-300 bg-cyan-300 text-[#061017]":"border-white/15 bg-white/[.04] text-white hover:border-cyan-300/40"}`}>{v.label} · {money(Number(v.price))}</button>})}</div></div>}
  <button disabled={unavailable} onClick={()=>{add({productId:product.id,slug:product.slug,name:product.name,image:product.images?.[0],variationLabel:variation?.label,price:final});setAdded(true);setTimeout(()=>setAdded(false),1600)}} className="button w-full disabled:cursor-not-allowed disabled:opacity-40">{unavailable?"Indisponible":added?<><Check size={19}/>Ajouté au panier</>:<><ShoppingBag size={19}/>Ajouter · {money(final)}</>}</button>
</div>}
