import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import { AddToCart } from "@/components/storefront/add-to-cart";
import { getCatalog } from "@/lib/data";
import { bestOffer, priceWithOffer } from "@/lib/offers";
import { money } from "@/lib/utils";
import { BrandLogo } from "@/components/brand-logo";
import { createWhatsAppUrl } from "@/lib/whatsapp";
import { FavoriteButton } from "@/components/storefront/favorite-button";
import { ProductImage } from "@/components/storefront/product-image";
export default async function ProductPage({params}:{params:{slug:string}}){const {products,offers,categories}=await getCatalog();const p=products.find(x=>x.slug===params.slug);if(!p)notFound();const category=categories.find(c=>c.id===p.category_id), offer=bestOffer(p,offers), price=priceWithOffer(Number(p.price),offer);return <div className="store-page"><div className="container-shell py-10"><div className="mb-7 text-xs text-white/45"><Link className="hover:text-cyan-300" href="/">Accueil</Link> / {category?.name} / <span className="text-white">{p.name}</span></div><div className="grid gap-10 lg:grid-cols-2">
  <div className="relative aspect-square overflow-hidden rounded-[1.5rem] border border-white/10 bg-white">{p.images?.[0]?<ProductImage src={p.images[0]} priority alt={p.name} sizes="(max-width: 1024px) 100vw, 50vw" className="p-5"/>:<div className="grid h-full place-items-center bg-[#0d151d] text-cyan-300/40">{<BrandLogo compact inverted/>}</div>}{offer&&<span className="absolute left-5 top-5 rounded-full bg-cyan-400 px-4 py-2 text-sm font-bold text-[#061017]">{offer.badge_text||offer.name}</span>}</div>
  <div className="flex flex-col justify-center lg:px-6"><div className="flex items-center justify-between gap-4"><p className="eyebrow">{category?.name||"Instrument"}</p><FavoriteButton productId={p.id}/></div><h1 className="display mt-3 text-5xl leading-tight">{p.name}</h1>{p.short_summary&&<p className="mt-3 text-lg text-white/55">{p.short_summary}</p>}<div className="mt-5 flex items-baseline gap-3"><span className="text-2xl font-bold text-cyan-300">{p.price_mode==="contact"?"Contactez-nous":money(Number(p.promotional_price||price))}</span>{p.promotional_price&&<span className="text-sm text-white/40 line-through">{money(Number(p.price))}</span>}</div><p className="mt-6 whitespace-pre-line leading-7 text-white/60">{p.description}</p>{Object.keys(p.technical_specs||{}).length>0&&<dl className="mt-6 grid gap-2 rounded-2xl border border-white/10 p-4 text-sm">{Object.entries(p.technical_specs||{}).map(([key,value])=><div key={key} className="flex justify-between gap-4"><dt className="text-white/45">{key}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl>}<div className="my-7 grid gap-2 border-y border-white/10 py-5 text-sm"><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-cyan-300"/>Qualité sélectionnée pour la pratique clinique</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-cyan-300"/>{(p.availability_status||p.stock_status)==="in_stock"?"En stock":(p.availability_status||p.stock_status)==="low_stock"?"Stock faible":(p.availability_status||p.stock_status)==="on_order"?"Disponible sur commande":"Indisponible"}</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-cyan-300"/>Livraison partout au Maroc</span></div>{p.price_mode==="contact"?<a href={createWhatsAppUrl(`Bonjour DENTANOVA, je souhaite connaître le prix de ${p.name}.`)} className="button w-full">Demander le prix sur WhatsApp</a>:<AddToCart product={p} price={Number(p.promotional_price||price)}/>}<p className="mt-3 text-center text-xs text-white/40">Confirmation et conseil personnalisé sur WhatsApp</p></div>
</div></div></div>}
