"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Archive, ArrowDown, ArrowUp, Check, Copy, Eye, ImagePlus, Loader2, Plus, Save, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient, hasSupabaseEnv } from "@/lib/supabase/client";
import { publicationReadiness, validateProduct, validateProductImage, type ProductDraft } from "@/lib/product-validation";
import { slugify } from "@/lib/utils";
import type { Category, Product, ProductImage, Variation } from "@/lib/types";

const emptyVariation=():Variation=>({id:crypto.randomUUID(),label:"",sku:"",attributes:{},price:0,stock_quantity:0,availability:"in_stock",is_active:true});
const datetime=(value?:string|null)=>value?new Date(value).toISOString().slice(0,16):"";

export function ProductForm({categories,product}:{categories:Category[];product?:Product}) {
  const router=useRouter(),formRef=useRef<HTMLFormElement>(null);
  const initialMedia:ProductImage[]=product?.image_metadata?.length?product.image_metadata:(product?.images||[]).map((url,index)=>({url,alt:product?.name||"Produit DENTANOVA",is_main:index===0}));
  const [media,setMedia]=useState(initialMedia),[removedUrls,setRemovedUrls]=useState<string[]>([]);
  const [variations,setVariations]=useState<Variation[]>(product?.variations||[]);
  const [dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
  const [message,setMessage]=useState(""),[errors,setErrors]=useState<Record<string,string>>({});
  const [publication,setPublication]=useState<ProductDraft["publication_status"]>(product?.publication_status||"draft");
  const [priceMode,setPriceMode]=useState<"fixed"|"contact">(product?.price_mode||"fixed");
  const [stockTracking,setStockTracking]=useState(Boolean(product?.stock_tracking));

  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);

  function draftFrom(form:HTMLFormElement):ProductDraft {
    const values=new FormData(form);
    return {
      name:String(values.get("name")||""),sku:String(values.get("sku")||""),slug:String(values.get("slug")||"")||slugify(String(values.get("name")||"")),
      category_id:String(values.get("category_id")||""),price:Number(values.get("price")||0),price_mode:priceMode,
      promotional_price:values.get("promotional_price")?Number(values.get("promotional_price")):null,
      promotion_starts_at:String(values.get("promotion_starts_at")||""),promotion_ends_at:String(values.get("promotion_ends_at")||""),
      stock_tracking:stockTracking,stock_quantity:Number(values.get("stock_quantity")||0),
      low_stock_threshold:Number(values.get("low_stock_threshold")||0),availability_status:String(values.get("availability_status")||"in_stock"),
      publication_status:publication,images:media,variations,
    };
  }

  async function upload(files:FileList|null){
    if(!files||!hasSupabaseEnv)return;setMessage("");
    const selected=Array.from(files);const invalid=selected.map(validateProductImage).find(Boolean);
    if(invalid){setMessage(invalid);return}setUploading(true);const db=createClient(),added:ProductImage[]=[];
    for(const file of selected){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),path=`products/${product?.id||"draft"}/${crypto.randomUUID()}-${safe}`;const {error}=await db.storage.from("product-images").upload(path,file,{contentType:file.type});if(!error){const url=db.storage.from("product-images").getPublicUrl(path).data.publicUrl;added.push({url,alt:product?.name||"Produit DENTANOVA",is_main:!media.length&&!added.length})}}
    setMedia(current=>[...current,...added]);setDirty(true);setUploading(false);if(added.length!==selected.length)setMessage("Certaines images n’ont pas pu être envoyées.");
  }

  function removeImage(index:number){if(!confirm("Retirer cette image du produit ? Elle sera supprimée du stockage après un enregistrement réussi."))return;const target=media[index];setRemovedUrls(old=>[...old,target.url]);const next=media.filter((_,i)=>i!==index);if(target.is_main&&next[0])next[0]={...next[0],is_main:true};setMedia(next);setDirty(true)}
  function moveImage(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=media.length)return;const next=[...media];[next[index],next[target]]=[next[target],next[index]];setMedia(next);setDirty(true)}
  function setMain(index:number){setMedia(current=>current.map((image,i)=>({...image,is_main:i===index})));setDirty(true)}

  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();if(!hasSupabaseEnv||saving)return;const form=event.currentTarget,draft=draftFrom(form),result=validateProduct(draft);
    if(!result.valid){setErrors(result.errors);setMessage("Corrigez les champs signalés avant d’enregistrer.");return}
    setErrors({});setSaving(true);setMessage("");const values=new FormData(form),db=createClient(),{data:{user}}=await db.auth.getUser();
    const specifications=String(values.get("technical_specs")||"").split("\n").map(line=>line.split(":")).filter(parts=>parts.length>1).reduce<Record<string,string>>((all,[key,...rest])=>({...all,[key.trim()]:rest.join(":").trim()}),{});
    const images=media.map(image=>image.url),main=media.find(image=>image.is_main);
    const payload={
      name:draft.name.trim(),sku:draft.sku.trim()||null,slug:draft.slug,brand:String(values.get("brand")||"").trim()||null,
      product_type:String(values.get("product_type")||"").trim()||null,short_summary:String(values.get("short_summary")||"").trim()||null,
      description:String(values.get("description")||"").trim()||null,technical_specs:specifications,condition:values.get("condition"),
      warranty:String(values.get("warranty")||"").trim()||null,category_id:draft.category_id||null,images,image_metadata:media,
      price:draft.price,compare_at_price:draft.price,price_mode:draft.price_mode,promotional_price:draft.promotional_price,
      promotion_starts_at:draft.promotion_starts_at||null,promotion_ends_at:draft.promotion_ends_at||null,
      stock_tracking:draft.stock_tracking,stock_quantity:draft.stock_quantity,low_stock_threshold:draft.low_stock_threshold,
      stock_status:draft.availability_status==="low_stock"?"in_stock":draft.availability_status==="unavailable"?"out_of_stock":draft.availability_status,
      availability_status:draft.availability_status,preparation_time:String(values.get("preparation_time")||"").trim()||null,
      internal_stock_note:String(values.get("internal_stock_note")||"").trim()||null,target_audience:values.get("target_audience"),
      variations,publication_status:draft.publication_status,search_visible:values.get("search_visible")==="on",
      catalog_visible:values.get("catalog_visible")==="on",is_active:draft.publication_status==="published",
      is_featured:values.get("is_featured")==="on",published_at:draft.publication_status==="published"?(product?.published_at||new Date().toISOString()):null,
      delivery_eligible:true,delivery_note:String(values.get("delivery_note")||"").trim()||null,pickup_available:false,
      seo_title:String(values.get("seo_title")||"").trim()||null,meta_description:String(values.get("meta_description")||"").trim()||null,
      og_image_url:String(values.get("og_image_url")||"").trim()||main?.url||null,updated_by:user?.id||null,
    };
    const response=product?await db.from("products").update(payload).eq("id",product.id).select("id").single():await db.from("products").insert(payload).select("id").single();
    if(response.error){setMessage("Impossible d’enregistrer le produit. Vérifiez le SKU et le slug.");setSaving(false);return}
    for(const url of removedUrls){const marker="/product-images/";const path=url.includes(marker)?decodeURIComponent(url.split(marker)[1].split("?")[0]):"";if(path)await db.storage.from("product-images").remove([path])}
    setRemovedUrls([]);setDirty(false);setSaving(false);setMessage("Produit enregistré.");
    if(!product)router.push(`/admin/products/${response.data.id}`);else router.refresh();
  }

  async function archive(){if(!product||!confirm("Archiver ce produit ? Il disparaîtra immédiatement du catalogue public, mais son historique sera conservé."))return;setSaving(true);const {error}=await createClient().from("products").update({publication_status:"archived",is_active:false,catalog_visible:false}).eq("id",product.id);setSaving(false);if(error)setMessage("Impossible d’archiver le produit.");else{setPublication("archived");setMessage("Produit archivé.");router.refresh()}}
  async function duplicate(){if(!product||!confirm("Créer une copie brouillon de ce produit ? Le stock et le SKU ne seront pas copiés."))return;setSaving(true);const db=createClient(),{id,created_at,updated_at,categories,...copy}=product as Product&Record<string,unknown>;const {data,error}=await db.from("products").insert({...copy,name:`${product.name} — copie`,slug:`${product.slug}-copie-${Date.now().toString().slice(-6)}`,sku:null,publication_status:"draft",is_active:false,stock_quantity:0,published_at:null,updated_by:(await db.auth.getUser()).data.user?.id||null}).select("id").single();setSaving(false);if(error)setMessage("Impossible de dupliquer le produit.");else router.push(`/admin/products/${data.id}`)}

  const readiness=formRef.current?publicationReadiness(draftFrom(formRef.current)):[];
  const field=(name:string,label:string,defaultValue:unknown=undefined,type="text")=><label className="admin-field">{label}<input name={name} type={type} defaultValue={(defaultValue??"") as string|number}/>{errors[name]&&<small role="alert">{errors[name]}</small>}</label>;
  return <div>
    <header className="mb-7"><div className="text-xs text-white/40"><Link href="/admin">Administration</Link> <span>/</span> <Link href="/admin/products">Produits</Link> <span>/</span> <b className="text-white">{product?.name||"Nouveau produit"}</b></div><div className="mt-5 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div className="flex min-w-0 items-center gap-4"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]">{media[0]?<Image src={media.find(image=>image.is_main)?.url||media[0].url} fill alt={media.find(image=>image.is_main)?.alt||product?.name||"Produit"} className="object-cover"/>:<span className="grid h-full place-items-center text-xs text-white/30">Aucune image</span>}</div><div className="min-w-0"><p className="eyebrow">Fiche produit</p><h1 className="display mt-1 truncate text-3xl md:text-4xl">{product?.name||"Nouveau produit"}</h1><div className="mt-2 flex flex-wrap gap-2"><span className="account-badge">{publication==="published"?"Publié":publication==="archived"?"Archivé":"Brouillon"}</span><span className="account-badge">{product?.availability_status||product?.stock_status||"En stock"}</span>{product?.sku&&<span className="text-xs text-white/40">SKU · {product.sku}</span>}</div></div></div><div className="flex flex-wrap gap-2">{product&&publication==="published"&&<Link href={`/product/${product.slug}`} className="account-button-secondary"><Eye size={16}/>Voir sur la boutique</Link>}{product&&<button onClick={duplicate} disabled={saving} className="account-button-secondary"><Copy size={16}/>Dupliquer</button>}{product&&publication!=="archived"&&<button onClick={archive} disabled={saving} className="account-danger-button"><Archive size={16}/>Archiver</button>}<button form="product-editor" disabled={saving} className="account-button">{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Enregistrer</button></div></div></header>
    <form id="product-editor" ref={formRef} onSubmit={submit} onChange={()=>setDirty(true)} className="product-editor-layout">
      <div className="product-editor-main">
        <Section title="Informations générales"><div className="grid gap-4 md:grid-cols-2">{field("name","Nom du produit",product?.name)}{field("sku","Référence interne / SKU",product?.sku)}{field("slug","Slug public",product?.slug||"")} {field("brand","Marque / fabricant",product?.brand)}{field("product_type","Type de produit",product?.product_type)}<label className="admin-field">Condition<select name="condition" defaultValue={product?.condition||"new"}><option value="new">Neuf</option><option value="refurbished">Reconditionné</option></select></label></div><label className="admin-field mt-4">Résumé court<textarea name="short_summary" rows={2} defaultValue={product?.short_summary||""}/></label><label className="admin-field mt-4">Description complète<textarea name="description" rows={7} defaultValue={product?.description||""}/></label><label className="admin-field mt-4">Spécifications techniques<textarea name="technical_specs" rows={6} defaultValue={Object.entries(product?.technical_specs||{}).map(([key,value])=>`${key}: ${value}`).join("\n")} placeholder={"Modèle: DN-100\nMatériau: Acier inoxydable"}/><span>Une caractéristique par ligne, sous la forme « nom: valeur ».</span></label><label className="admin-field mt-4">Garantie<input name="warranty" defaultValue={product?.warranty||""}/></label></Section>
        <Section title="Images et médias"><label className="admin-upload"><ImagePlus/><b>{uploading?"Envoi en cours…":"Ajouter des images"}</b><span>JPEG, PNG ou WebP · 5 Mo maximum</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files)} disabled={uploading}/></label>{errors.images&&<p className="mt-3 text-sm text-red-300">{errors.images}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{media.map((image,index)=><div key={image.url} className="rounded-2xl border border-white/10 bg-white/[.025] p-3"><div className="relative aspect-video overflow-hidden rounded-xl bg-white/[.04]"><Image src={image.url} alt={image.alt||"Image produit"} fill className="object-cover"/>{image.is_main&&<span className="absolute left-2 top-2 account-badge">Principale</span>}</div><label className="admin-field mt-3">Texte alternatif<input value={image.alt} onChange={event=>{setMedia(current=>current.map((item,i)=>i===index?{...item,alt:event.target.value}:item));setDirty(true)}}/></label><div className="mt-3 flex gap-2"><button type="button" onClick={()=>setMain(index)} className="admin-icon-button" aria-label="Définir comme image principale"><Check size={15}/></button><button type="button" onClick={()=>moveImage(index,-1)} className="admin-icon-button" aria-label="Déplacer vers le haut"><ArrowUp size={15}/></button><button type="button" onClick={()=>moveImage(index,1)} className="admin-icon-button" aria-label="Déplacer vers le bas"><ArrowDown size={15}/></button><button type="button" onClick={()=>removeImage(index)} className="admin-icon-button danger ml-auto" aria-label="Retirer l’image"><Trash2 size={15}/></button></div></div>)}</div></Section>
        <Section title="Variations"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th>Nom</th><th>SKU</th><th>Attributs</th><th>Prix MAD</th><th>Stock</th><th>État</th><th/></tr></thead><tbody>{variations.map((variation,index)=><tr key={variation.id||index}><td><input className="field" value={variation.label} onChange={e=>setVariations(current=>current.map((item,i)=>i===index?{...item,label:e.target.value}:item))}/></td><td><input className="field" value={variation.sku||""} onChange={e=>setVariations(current=>current.map((item,i)=>i===index?{...item,sku:e.target.value}:item))}/></td><td><input className="field" placeholder="Taille=M; Couleur=Bleu" value={Object.entries(variation.attributes||{}).map(([key,value])=>`${key}=${value}`).join("; ")} onChange={e=>setVariations(current=>current.map((item,i)=>i===index?{...item,attributes:Object.fromEntries(e.target.value.split(";").map(part=>part.split("=").map(value=>value.trim())).filter(pair=>pair.length===2))}:item))}/></td><td><input className="field" type="number" min="0" step=".01" value={variation.price} onChange={e=>setVariations(current=>current.map((item,i)=>i===index?{...item,price:Number(e.target.value)}:item))}/></td><td><input className="field" type="number" min="0" value={variation.stock_quantity||0} onChange={e=>setVariations(current=>current.map((item,i)=>i===index?{...item,stock_quantity:Number(e.target.value)}:item))}/></td><td><button type="button" className="account-badge" onClick={()=>setVariations(current=>current.map((item,i)=>i===index?{...item,is_active:item.is_active===false}:item))}>{variation.is_active===false?"Archivée":"Active"}</button></td><td><div className="flex"><button type="button" className="admin-icon-button" onClick={()=>setVariations(current=>[...current.slice(0,index+1),{...variation,id:crypto.randomUUID(),sku:""},...current.slice(index+1)])}><Copy size={14}/></button><button type="button" className="admin-icon-button danger" onClick={()=>setVariations(current=>current.filter((_,i)=>i!==index))}><X size={14}/></button></div></td></tr>)}</tbody></table></div>{errors.variations&&<p className="mt-3 text-sm text-red-300">{errors.variations}</p>}<button type="button" onClick={()=>{setVariations(current=>[...current,emptyVariation()]);setDirty(true)}} className="account-button-secondary mt-4"><Plus size={16}/>Ajouter une variation</button></Section>
        <Section title="SEO et aperçu public"><div className="grid gap-4">{field("seo_title","Titre SEO",product?.seo_title)}<label className="admin-field">Méta-description<textarea name="meta_description" rows={3} maxLength={160} defaultValue={product?.meta_description||""}/></label>{field("og_image_url","Image Open Graph",product?.og_image_url)}</div><div className="mt-5 rounded-2xl border border-white/10 bg-[var(--dn-bg-raised)] p-5"><p className="text-sm text-cyan-300">{product?.seo_title||product?.name||"Titre du produit"} · DENTANOVA</p><p className="mt-1 text-xs text-emerald-300">dental-market-bay.vercel.app/product/{product?.slug||"slug"}</p><p className="mt-2 text-sm text-white/50">{product?.meta_description||product?.short_summary||"La description SEO apparaîtra ici."}</p></div></Section>
      </div>
      <aside className="product-editor-sidebar">
        <Section title="Publication"><label className="admin-field">Statut<select value={publication} onChange={e=>{setPublication(e.target.value as ProductDraft["publication_status"]);setDirty(true)}}><option value="draft">Brouillon</option><option value="published">Publié</option><option value="archived">Archivé</option></select></label><label className="admin-check"><input type="checkbox" name="catalog_visible" defaultChecked={product?.catalog_visible!==false}/>Visible dans le catalogue</label><label className="admin-check"><input type="checkbox" name="search_visible" defaultChecked={product?.search_visible!==false}/>Visible dans la recherche</label><label className="admin-check"><input type="checkbox" name="is_featured" defaultChecked={product?.is_featured}/>Produit mis en avant</label><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Prêt à publier</p><div className="mt-3 grid gap-2">{readiness.map(([label,ready])=><p key={label} className="flex items-center gap-2 text-xs"><span className={ready?"text-emerald-300":"text-white/25"}>{ready?<Check size={14}/>:<X size={14}/>}</span>{label}</p>)}</div></div></Section>
        <Section title="Catégorie et audience"><label className="admin-field">Catégorie principale<select name="category_id" defaultValue={product?.category_id||""}><option value="">Sélectionner</option>{categories.map(category=><option key={category.id} value={category.id}>{category.parent_id?"— ":""}{category.name}</option>)}</select>{errors.category_id&&<small>{errors.category_id}</small>}</label><label className="admin-field mt-4">Audience<select name="target_audience" defaultValue={product?.target_audience||"both"}><option value="both">Tous les professionnels</option><option value="student">Étudiants</option><option value="professional">Professionnels</option></select></label></Section>
        <Section title="Tarification"><label className="admin-field">Mode de prix<select value={priceMode} onChange={e=>{setPriceMode(e.target.value as "fixed"|"contact");setDirty(true)}}><option value="fixed">Prix affiché</option><option value="contact">Contactez-nous</option></select></label>{field("price","Prix standard · MAD",product?.price||0,"number")}{errors.price&&<p className="text-xs text-red-300">{errors.price}</p>}{field("promotional_price","Prix promotionnel · MAD",product?.promotional_price||product?.compare_at_price,"number")}<div className="grid grid-cols-2 gap-3">{field("promotion_starts_at","Début",datetime(product?.promotion_starts_at),"datetime-local")}{field("promotion_ends_at","Fin",datetime(product?.promotion_ends_at),"datetime-local")}</div><p className="mt-4 rounded-xl bg-white/[.04] p-3 text-sm">Aperçu : <b className="text-cyan-300">{priceMode==="contact"?"Contactez-nous":`${product?.promotional_price||product?.price||0} MAD`}</b></p></Section>
        <Section title="Stock et disponibilité"><label className="admin-check"><input type="checkbox" checked={stockTracking} onChange={e=>{setStockTracking(e.target.checked);setDirty(true)}}/>Suivre le stock</label><label className="admin-field mt-4">Disponibilité<select name="availability_status" defaultValue={product?.availability_status||product?.stock_status||"in_stock"}><option value="in_stock">En stock</option><option value="low_stock">Stock faible</option><option value="out_of_stock">Rupture de stock</option><option value="on_order">Sur commande</option><option value="unavailable">Indisponible</option></select>{errors.availability_status&&<small>{errors.availability_status}</small>}</label><div className="mt-4 grid grid-cols-2 gap-3">{field("stock_quantity","Quantité",product?.stock_quantity||0,"number")}{field("low_stock_threshold","Seuil faible",product?.low_stock_threshold||3,"number")}</div>{field("preparation_time","Délai de préparation",product?.preparation_time)}<label className="admin-field">Note interne<textarea name="internal_stock_note" rows={3} defaultValue={product?.internal_stock_note||""}/></label></Section>
        <Section title="Livraison"><div className="status-success rounded-xl p-3 text-sm font-bold">Livraison disponible partout au Maroc.</div><input type="hidden" name="delivery_eligible" value="true"/><label className="admin-field mt-4">Note de livraison<textarea name="delivery_note" rows={3} defaultValue={product?.delivery_note||""}/></label></Section>
        {product&&<Section title="Métadonnées"><dl className="grid gap-3 text-xs"><Meta label="Identifiant" value="Référence interne protégée"/><Meta label="Créé le" value={product.created_at?new Date(product.created_at).toLocaleString("fr-MA"):"—"}/><Meta label="Dernière mise à jour" value={product.updated_at?new Date(product.updated_at).toLocaleString("fr-MA"):"—"}/><Meta label="Publié le" value={product.published_at?new Date(product.published_at).toLocaleString("fr-MA"):"Non publié"}/><Meta label="État base" value={publication}/></dl></Section>}
      </aside>
    </form>
    {message&&<div role="status" className={`fixed bottom-5 right-5 z-50 max-w-sm rounded-2xl p-4 shadow-2xl ${message.includes("Impossible")||message.includes("Corrigez")?"status-error":"status-success"}`}>{message}</div>}
    {dirty&&<div className="sticky bottom-4 z-30 mx-auto mt-6 flex max-w-md items-center justify-between rounded-full border border-amber-300/20 bg-[var(--dn-warning-surface)] px-5 py-3 text-sm shadow-2xl backdrop-blur"><span>Modifications non enregistrées</span><button form="product-editor" className="text-sm font-bold text-cyan-300">Enregistrer</button></div>}
  </div>
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card product-editor-section p-5 md:p-6"><h2 className="break-words text-lg font-black">{title}</h2><div className="mt-5 min-w-0">{children}</div></section>}
function Meta({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b border-white/[.07] pb-2"><dt className="text-white/40">{label}</dt><dd className="text-right font-bold">{value}</dd></div>}
